### ISSUE TITLE
Cacher le mdp lors de la connexion

### ISSUE THREAD

**Issue by Hagbuck** [Hagbuck/project-designer#10]
Dans le formulaire de connexion, il faut remplacer le texte tapé par l'utilisateur par des étoiles.

**Comment by Drainman** [comment]
C'est du Front, je m'en charge !

**Comment by Hagbuck** [comment]
J'avais un peu de temps et d'envie alors je m'en suis occupé.

J'ai juste changer la *queue* du swal de la connexion : 

```
queue([
    {
      title: 'Vos identifiants',
      text: 'Identifiant'
    },
    {
      title: 'Vos identifiants',
      text: 'Mot de Passe',
      input: 'password'
    }
  ])
```

**Comment by Hagbuck** [comment]
C'est déployé sur le git et en prod ;)

**Comment by Drainman** [comment]
GG ! Close !
