### ISSUE TITLE
La sauvegarde des positions n'est plus mis à jour dans la DB

### ISSUE THREAD

**Issue by Hagbuck** [Hagbuck/project-designer#15]
Erreur d'envoi ou de traitement de donnée ?

**Comment by Drainman** [comment]
En lien avec l'issu #11 ;)

**Comment by Hagbuck** [comment]
Le script de création donne gérait les position comme suit 
```
pos_x_tag float(10,10),
pos_y_tag float(10,10),
```

Ce qui autorisait nos position entre -1 et 1 avec 10 chiffres derrière la virgule. Je ne comprend même pas comment ça a pus marché.

J'ai remplacé par des valeur entière que sont les positions : 

```
pos_x_tag SMALLINT,
pos_y_tag SMALLINT,
```

La sauvegarde de position refonctionne donc.
