### ISSUE TITLE
Les branches s'affichent souvent après les tags

### ISSUE THREAD

**Issue by Hagbuck** [Hagbuck/project-designer#17]
Il faudrait pour des raisons esthetique que les branches s'affichent en premier.

**Comment by Hagbuck** [comment]
Comme ça touche à Konvas je vais mis coller ;)

**Comment by Drainman** [comment]
Huuuum, on l'envoie en base mais on demande pas d'afficher derrière.
Je me souviens que c'était déjà comme ça avant, on devait actualiser ! 
A voir donc dans la fonction JS après l'appel AJAX.

**Comment by Hagbuck** [comment]
J'ai ajouter un callBack dans la fonction display_branch pour lancer en synchrone les deux fonctions d'affichage.

```
function valid_access(projet,diag)
{
  header_diagramme(diag);
  header_project(projet);
  display_branch(diag, function(){
    display_tags(diag); 
  });

  $('#new_tag').attr("onclick","newTag("+diag+")")
  $('#new_branch').attr("onclick","newBranch("+diag+")")
  $('#del_branch').attr("onclick","delBranch("+diag+")")

}
```
