### ISSUE TITLE
[Proposition] - Convert canva to print document

### ISSUE THREAD

**Issue by Drainman** [Hagbuck/project-designer#3]
Ce serait super de proposer l'impression d'un diagramme.
De super lib permettent de faire ça en quelques lignes :)

**Comment by Hagbuck** [comment]
J'avooooooouuuuuuuuuue !

**Comment by Hagbuck** [comment]
On peut déjà enregistrer le diagramme en image. Il faudra ajouter d'autre affichage quand le proejt aura évolué. On réouvrira le ticket.
