### ISSUE TITLE
Chiffrement des mots de passe

### ISSUE THREAD

**Issue by Hagbuck** [Hagbuck/project-designer#9]
Il faut chiffrer les mdp en SHA ou MD5 le plus rapidement possible, avant que project-designer devienne l'outil numero1 dans le monde ! :p

**Comment by Drainman** [comment]
Tout à fait d'accord xD
Aprés si on pouvait mettre un petit HTTPS ce serait sympa ! 
Mais c'est coté hébergeur ça...

**Comment by Hagbuck** [comment]
Chiffrement en SHA1 OK. J'ai du réinitialisé la base afin que nos mdp passe bien vue qu'on a pas encore instauré de système pour changer son mdp (porchaine issue is comming ^^)
